void sipmCharge_analysis2(){
	gStyle->SetOptStat(kFALSE);
//	gStyle->SetOptFit(1);
//	gStyle->SetOptStat(1110);

	TCanvas* c1 = new TCanvas("c1", "First canvas", 800,600);
	TF1* gauF = new TF1("gauF","gaus",-50,50);
	c1->SetFillColor(0);
	c1->SetFrameFillStyle(0);

	//////////////
	// LXSC2_Z2 //
	//////////////
	TFile *file = TFile::Open("lxsc2_z2.root");
	petAnalysis_SiPMMC_Plane0->RebinY(20);
	petAnalysis_SiPMMC_Plane0->SetAxisRange(-10.,10.,"X");
	petAnalysis_SiPMMC_Plane0->SetAxisRange(0.,3000.,"Y");
	petAnalysis_SiPMMC_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_p0_2_z2.pdf");
	petAnalysis_SiPMMC_Plane2->RebinY(20);
	petAnalysis_SiPMMC_Plane2->SetAxisRange(-10.,10.,"X");
	petAnalysis_SiPMMC_Plane2->SetAxisRange(0.,3000.,"Y");
	petAnalysis_SiPMMC_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_p2_2_z2.pdf");

	petAnalysis_SiPMMC_C1_Plane0->RebinY(20);
	petAnalysis_SiPMMC_C1_Plane0->SetAxisRange(-10.,10.,"X");
	petAnalysis_SiPMMC_C1_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C1_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C1_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C1_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_c1_p0_2_z2.pdf");
	petAnalysis_SiPMMC_C1_Plane2->RebinY(20);
	petAnalysis_SiPMMC_C1_Plane2->SetAxisRange(-10.,10.,"X");
	petAnalysis_SiPMMC_C1_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C1_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C1_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C1_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_c1_p2_2_z2.pdf");

	petAnalysis_SiPMMC_C2_Plane0->RebinY(20);
	petAnalysis_SiPMMC_C2_Plane0->SetAxisRange(-10.,10.,"X");
	petAnalysis_SiPMMC_C2_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C2_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C2_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C2_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_c2_p0_2_z2.pdf");
	petAnalysis_SiPMMC_C2_Plane2->RebinY(20);
	petAnalysis_SiPMMC_C2_Plane2->SetAxisRange(-10.,10.,"X");
	petAnalysis_SiPMMC_C2_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C2_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C2_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C2_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_c2_p2_2_z2.pdf");

	petAnalysis_Plane0_NoSiPMMC->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC->SetAxisRange(-10.,10.,"X");
	petAnalysis_Plane0_NoSiPMMC->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC->Draw("colz");
	c1->Print("deliverables2/nosipmmc_p0_2_z2.pdf");
	petAnalysis_Plane2_NoSiPMMC->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC->SetAxisRange(-10.,10.,"X");
	petAnalysis_Plane2_NoSiPMMC->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC->Draw("colz");
	c1->Print("deliverables2/nosipmmc_p2_2_z2.pdf");

	petAnalysis_Plane0_NoSiPMMC_C1->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC_C1->SetAxisRange(-10.,10.,"X");
	petAnalysis_Plane0_NoSiPMMC_C1->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC_C1->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC_C1->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC_C1->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c1_p0_2_z2.pdf");
	petAnalysis_Plane2_NoSiPMMC_C1->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC_C1->SetAxisRange(-10.,10.,"X");
	petAnalysis_Plane2_NoSiPMMC_C1->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC_C1->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC_C1->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC_C1->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c1_p2_2_z2.pdf");

	petAnalysis_Plane0_NoSiPMMC_C2->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC_C2->SetAxisRange(-10.,10.,"X");
	petAnalysis_Plane0_NoSiPMMC_C2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC_C2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC_C2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC_C2->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c2_p0_2_z2.pdf");
	petAnalysis_Plane2_NoSiPMMC_C2->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC_C2->SetAxisRange(-10.,10.,"X");
	petAnalysis_Plane2_NoSiPMMC_C2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC_C2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC_C2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC_C2->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c2_p2_2_z2.pdf");

	petAnalysis_Plane0->RebinY(20);
	petAnalysis_Plane0->SetAxisRange(-10.,10.,"X");
	petAnalysis_Plane0->SetAxisRange(0.,6500.,"Y");
	petAnalysis_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0->Draw("colz");
	c1->Print("deliverables2/plane0_2_z2.pdf");
	petAnalysis_Plane2->RebinY(20);
	petAnalysis_Plane2->SetAxisRange(-10.,10.,"X");
	petAnalysis_Plane2->SetAxisRange(0.,6500.,"Y");
	petAnalysis_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2->Draw("colz");
	c1->Print("deliverables2/plane2_2_z2.pdf");
	file->Close();

	//////////////
	// LXSC2_Z3 //
	//////////////
	TFile *file = TFile::Open("lxsc2_z3.root");
	petAnalysis_SiPMMC_Plane0->RebinY(20);
	petAnalysis_SiPMMC_Plane0->SetAxisRange(-15.,15.,"X");
	petAnalysis_SiPMMC_Plane0->SetAxisRange(0.,3000.,"Y");
	petAnalysis_SiPMMC_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_p0_2_z3.pdf");
	petAnalysis_SiPMMC_Plane2->RebinY(20);
	petAnalysis_SiPMMC_Plane2->SetAxisRange(-15.,15.,"X");
	petAnalysis_SiPMMC_Plane2->SetAxisRange(0.,3000.,"Y");
	petAnalysis_SiPMMC_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_p2_2_z3.pdf");

	petAnalysis_SiPMMC_C1_Plane0->RebinY(20);
	petAnalysis_SiPMMC_C1_Plane0->SetAxisRange(-15.,15.,"X");
	petAnalysis_SiPMMC_C1_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C1_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C1_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C1_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_c1_p0_2_z3.pdf");
	petAnalysis_SiPMMC_C1_Plane2->RebinY(20);
	petAnalysis_SiPMMC_C1_Plane2->SetAxisRange(-15.,15.,"X");
	petAnalysis_SiPMMC_C1_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C1_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C1_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C1_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_c1_p2_2_z3.pdf");

	petAnalysis_SiPMMC_C2_Plane0->RebinY(20);
	petAnalysis_SiPMMC_C2_Plane0->SetAxisRange(-15.,15.,"X");
	petAnalysis_SiPMMC_C2_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C2_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C2_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C2_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_c2_p0_2_z3.pdf");
	petAnalysis_SiPMMC_C2_Plane2->RebinY(20);
	petAnalysis_SiPMMC_C2_Plane2->SetAxisRange(-15.,15.,"X");
	petAnalysis_SiPMMC_C2_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C2_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C2_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C2_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_c2_p2_2_z3.pdf");

	petAnalysis_Plane0_NoSiPMMC->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC->SetAxisRange(-15.,15.,"X");
	petAnalysis_Plane0_NoSiPMMC->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC->Draw("colz");
	c1->Print("deliverables2/nosipmmc_p0_2_z3.pdf");
	petAnalysis_Plane2_NoSiPMMC->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC->SetAxisRange(-15.,15.,"X");
	petAnalysis_Plane2_NoSiPMMC->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC->Draw("colz");
	c1->Print("deliverables2/nosipmmc_p2_2_z3.pdf");

	petAnalysis_Plane0_NoSiPMMC_C1->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC_C1->SetAxisRange(-15.,15.,"X");
	petAnalysis_Plane0_NoSiPMMC_C1->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC_C1->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC_C1->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC_C1->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c1_p0_2_z3.pdf");
	petAnalysis_Plane2_NoSiPMMC_C1->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC_C1->SetAxisRange(-15.,15.,"X");
	petAnalysis_Plane2_NoSiPMMC_C1->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC_C1->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC_C1->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC_C1->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c1_p2_2_z3.pdf");

	petAnalysis_Plane0_NoSiPMMC_C2->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC_C2->SetAxisRange(-15.,15.,"X");
	petAnalysis_Plane0_NoSiPMMC_C2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC_C2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC_C2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC_C2->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c2_p0_2_z3.pdf");
	petAnalysis_Plane2_NoSiPMMC_C2->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC_C2->SetAxisRange(-15.,15.,"X");
	petAnalysis_Plane2_NoSiPMMC_C2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC_C2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC_C2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC_C2->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c2_p2_2_z3.pdf");

	petAnalysis_Plane0->RebinY(20);
	petAnalysis_Plane0->SetAxisRange(-15.,15.,"X");
	petAnalysis_Plane0->SetAxisRange(0.,6500.,"Y");
	petAnalysis_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0->Draw("colz");
	c1->Print("deliverables2/plane0_2_z3.pdf");
	petAnalysis_Plane2->RebinY(20);
	petAnalysis_Plane2->SetAxisRange(-15.,15.,"X");
	petAnalysis_Plane2->SetAxisRange(0.,6500.,"Y");
	petAnalysis_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2->Draw("colz");
	c1->Print("deliverables2/plane2_2_z3.pdf");
	file->Close();

	//////////////
	// LXSC2_Z4 //
	//////////////
	TFile *file = TFile::Open("lxsc2_z4.root");
	petAnalysis_SiPMMC_Plane0->RebinY(20);
	petAnalysis_SiPMMC_Plane0->SetAxisRange(-20.,20.,"X");
	petAnalysis_SiPMMC_Plane0->SetAxisRange(0.,3000.,"Y");
	petAnalysis_SiPMMC_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_p0_2_z4.pdf");
	petAnalysis_SiPMMC_Plane2->RebinY(20);
	petAnalysis_SiPMMC_Plane2->SetAxisRange(-20.,20.,"X");
	petAnalysis_SiPMMC_Plane2->SetAxisRange(0.,3000.,"Y");
	petAnalysis_SiPMMC_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_p2_2_z4.pdf");

	petAnalysis_SiPMMC_C1_Plane0->RebinY(20);
	petAnalysis_SiPMMC_C1_Plane0->SetAxisRange(-20.,20.,"X");
	petAnalysis_SiPMMC_C1_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C1_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C1_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C1_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_c1_p0_2_z4.pdf");
	petAnalysis_SiPMMC_C1_Plane2->RebinY(20);
	petAnalysis_SiPMMC_C1_Plane2->SetAxisRange(-20.,20.,"X");
	petAnalysis_SiPMMC_C1_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C1_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C1_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C1_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_c1_p2_2_z4.pdf");

	petAnalysis_SiPMMC_C2_Plane0->RebinY(20);
	petAnalysis_SiPMMC_C2_Plane0->SetAxisRange(-20.,20.,"X");
	petAnalysis_SiPMMC_C2_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C2_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C2_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C2_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_c2_p0_2_z4.pdf");
	petAnalysis_SiPMMC_C2_Plane2->RebinY(20);
	petAnalysis_SiPMMC_C2_Plane2->SetAxisRange(-20.,20.,"X");
	petAnalysis_SiPMMC_C2_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C2_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C2_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C2_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_c2_p2_2_z4.pdf");

	petAnalysis_Plane0_NoSiPMMC->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC->SetAxisRange(-20.,20.,"X");
	petAnalysis_Plane0_NoSiPMMC->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC->Draw("colz");
	c1->Print("deliverables2/nosipmmc_p0_2_z4.pdf");
	petAnalysis_Plane2_NoSiPMMC->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC->SetAxisRange(-20.,20.,"X");
	petAnalysis_Plane2_NoSiPMMC->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC->Draw("colz");
	c1->Print("deliverables2/nosipmmc_p2_2_z4.pdf");

	petAnalysis_Plane0_NoSiPMMC_C1->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC_C1->SetAxisRange(-20.,20.,"X");
	petAnalysis_Plane0_NoSiPMMC_C1->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC_C1->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC_C1->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC_C1->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c1_p0_2_z4.pdf");
	petAnalysis_Plane2_NoSiPMMC_C1->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC_C1->SetAxisRange(-20.,20.,"X");
	petAnalysis_Plane2_NoSiPMMC_C1->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC_C1->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC_C1->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC_C1->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c1_p2_2_z4.pdf");

	petAnalysis_Plane0_NoSiPMMC_C2->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC_C2->SetAxisRange(-20.,20.,"X");
	petAnalysis_Plane0_NoSiPMMC_C2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC_C2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC_C2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC_C2->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c2_p0_2_z4.pdf");
	petAnalysis_Plane2_NoSiPMMC_C2->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC_C2->SetAxisRange(-20.,20.,"X");
	petAnalysis_Plane2_NoSiPMMC_C2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC_C2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC_C2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC_C2->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c2_p2_2_z4.pdf");

	petAnalysis_Plane0->RebinY(20);
	petAnalysis_Plane0->SetAxisRange(-20.,20.,"X");
	petAnalysis_Plane0->SetAxisRange(0.,6500.,"Y");
	petAnalysis_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0->Draw("colz");
	c1->Print("deliverables2/plane0_2_z4.pdf");
	petAnalysis_Plane2->RebinY(20);
	petAnalysis_Plane2->SetAxisRange(-20.,20.,"X");
	petAnalysis_Plane2->SetAxisRange(0.,6500.,"Y");
	petAnalysis_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2->Draw("colz");
	c1->Print("deliverables2/plane2_2_z4.pdf");
	file->Close();
	
	//////////////
	// LXSC2_Z5 //
	//////////////
	TFile *file = TFile::Open("lxsc2_z5.root");
	petAnalysis_SiPMMC_Plane0->RebinY(20);
	petAnalysis_SiPMMC_Plane0->SetAxisRange(-25.,25.,"X");
	petAnalysis_SiPMMC_Plane0->SetAxisRange(0.,3000.,"Y");
	petAnalysis_SiPMMC_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_p0_2_z5.pdf");
	petAnalysis_SiPMMC_Plane2->RebinY(20);
	petAnalysis_SiPMMC_Plane2->SetAxisRange(-25.,25.,"X");
	petAnalysis_SiPMMC_Plane2->SetAxisRange(0.,3000.,"Y");
	petAnalysis_SiPMMC_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_p2_2_z5.pdf");

	petAnalysis_SiPMMC_C1_Plane0->RebinY(20);
	petAnalysis_SiPMMC_C1_Plane0->SetAxisRange(-25.,25.,"X");
	petAnalysis_SiPMMC_C1_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C1_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C1_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C1_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_c1_p0_2_z5.pdf");
	petAnalysis_SiPMMC_C1_Plane2->RebinY(20);
	petAnalysis_SiPMMC_C1_Plane2->SetAxisRange(-25.,25.,"X");
	petAnalysis_SiPMMC_C1_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C1_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C1_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C1_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_c1_p2_2_z5.pdf");

	petAnalysis_SiPMMC_C2_Plane0->RebinY(20);
	petAnalysis_SiPMMC_C2_Plane0->SetAxisRange(-25.,25.,"X");
	petAnalysis_SiPMMC_C2_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C2_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C2_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C2_Plane0->Draw("colz");
	c1->Print("deliverables2/sipmmc_c2_p0_2_z5.pdf");
	petAnalysis_SiPMMC_C2_Plane2->RebinY(20);
	petAnalysis_SiPMMC_C2_Plane2->SetAxisRange(-25.,25.,"X");
	petAnalysis_SiPMMC_C2_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_SiPMMC_C2_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_SiPMMC_C2_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_SiPMMC_C2_Plane2->Draw("colz");
	c1->Print("deliverables2/sipmmc_c2_p2_2_z5.pdf");

	petAnalysis_Plane0_NoSiPMMC->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC->SetAxisRange(-25.,25.,"X");
	petAnalysis_Plane0_NoSiPMMC->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC->Draw("colz");
	c1->Print("deliverables2/nosipmmc_p0_2_z5.pdf");
	petAnalysis_Plane2_NoSiPMMC->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC->SetAxisRange(-25.,25.,"X");
	petAnalysis_Plane2_NoSiPMMC->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC->Draw("colz");
	c1->Print("deliverables2/nosipmmc_p2_2_z5.pdf");

	petAnalysis_Plane0_NoSiPMMC_C1->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC_C1->SetAxisRange(-25.,25.,"X");
	petAnalysis_Plane0_NoSiPMMC_C1->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC_C1->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC_C1->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC_C1->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c1_p0_2_z5.pdf");
	petAnalysis_Plane2_NoSiPMMC_C1->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC_C1->SetAxisRange(-25.,25.,"X");
	petAnalysis_Plane2_NoSiPMMC_C1->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC_C1->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC_C1->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC_C1->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c1_p2_2_z5.pdf");

	petAnalysis_Plane0_NoSiPMMC_C2->RebinY(20);
	petAnalysis_Plane0_NoSiPMMC_C2->SetAxisRange(-25.,25.,"X");
	petAnalysis_Plane0_NoSiPMMC_C2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0_NoSiPMMC_C2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0_NoSiPMMC_C2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0_NoSiPMMC_C2->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c2_p0_2_z5.pdf");
	petAnalysis_Plane2_NoSiPMMC_C2->RebinY(20);
	petAnalysis_Plane2_NoSiPMMC_C2->SetAxisRange(-25.,25.,"X");
	petAnalysis_Plane2_NoSiPMMC_C2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2_NoSiPMMC_C2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2_NoSiPMMC_C2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2_NoSiPMMC_C2->Draw("colz");
	c1->Print("deliverables2/nosipmmc_c2_p2_2_z5.pdf");

	petAnalysis_Plane0->RebinY(20);
	petAnalysis_Plane0->SetAxisRange(-25.,25.,"X");
	petAnalysis_Plane0->SetAxisRange(0.,6500.,"Y");
	petAnalysis_Plane0->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane0->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane0->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane0->Draw("colz");
	c1->Print("deliverables2/plane0_2_z5.pdf");
	petAnalysis_Plane2->RebinY(20);
	petAnalysis_Plane2->SetAxisRange(-25.,25.,"X");
	petAnalysis_Plane2->SetAxisRange(0.,6500.,"Y");
	petAnalysis_Plane2->GetXaxis()->SetTitle("z (mm)");
	petAnalysis_Plane2->GetYaxis()->SetTitleOffset(1.4);
	petAnalysis_Plane2->GetYaxis()->SetTitle("pes");
	petAnalysis_Plane2->Draw("colz");
	c1->Print("deliverables2/plane2_2_z5.pdf");
	file->Close();

	c1->Close();
}
